### ISSUE TITLE
Assertion Error on initial run

### ISSUE THREAD

**Issue by leesoh** [lair-framework/lair#94]
Hi there,

Right after I tried running the service I got the following error:
```
guy@thing:/opt/lair/bundle$ node main.js

assert.js:93
  throw new assert.AssertionError({
        ^
AssertionError: "undefined" === "function"
    at wrapPathFunction (/opt/lair/bundle/programs/server/mini-files.js:77:10)
    at Object.<anonymous> (/opt/lair/bundle/programs/server/mini-files.js:108:24)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/opt/lair/bundle/programs/server/boot.js:9:13)
    at Module._compile (module.js:456:26)
```

Any idea what's going on? Using Debian currently, will try again on Ubuntu.

**Comment by tomsteele** [comment]
Hi @leesoh, the reason for this is you are trying to run version v2.5.0 of lair, which we are still testing. You can run it with the latest version of node, which is currently v6.9.1. If you try to run v2.5.0 with the node version from the wiki it will throw this error.

I've been testing this version for a while tho, and everything seems ok, so I'll go ahead and update the wiki for the latest instructions. Thanks.

**Comment by leesoh** [comment]
Ahh, sorry! I figured the installation wiki was just out of date. Cheers!

**Comment by tomsteele** [comment]
Just updated it, enjoy fresh new meteor/lair/node 😃

**Comment by leesoh** [comment]
<3
